name: CI/CD with Github Actions

on:
    push:
      branches: ['*']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            working-directory: ./front-end
            - run: npm ci
            - run: npm run test:chrome
            - run: npm run build
